@baseUrl = http://localhost:3333

# @name get_courses
GET {{baseUrl}}/courses

###
# @name get_courses_with_search_filter
GET {{baseUrl}}/courses?search=react

###

# @name get_courses_with_orderBy_filter
GET {{baseUrl}}/courses?orderBy=title

###
# @name get_courses_with_page_filter
GET {{baseUrl}}/courses?page=3

### 

# @name get_course_by_id
GET {{baseUrl}}/courses/67970ee5-f838-4741-a328-6b5c39625806
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmM2OTRlOC1hNjhmLTRhNTMtYjhjNC0yMDgxZjMzODc1OGYiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NjA0NDkzNn0.176a-l_8Ms-pWxOgMHq2VhQXavk6ouM80HHOLMu7_r0

###

# @name create_course
POST {{baseUrl}}/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmM2OTRlOC1hNjhmLTRhNTMtYjhjNC0yMDgxZjMzODc1OGYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NjA0NjcyNn0.FfliMU6XvTigzT7iSRCP_CceaXjyFpsFYaqkwFuk-24

{
  "title": "Curso de Python"
}

###

# @name login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "Lucca4@yahoo.com",
  "password": "12345678"
}
